### ISSUE TITLE
With options not being respected

### ISSUE THREAD

**Issue by lucasjamar** [WaylonWalker/kedro-action#2]
Hi,

Thanks for the great action template. It makes implementing CI much simpler especially for someone with no real knowledge of CI/ CD.
However I am getting some issues with the options. They seem to be ignored. For instance, my kedro-action.yml looks like this:

```
name: kedro

on:
  push:
    branches:
      - main

jobs:
  kedro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Kedro
      uses: WaylonWalker/kedro-action@develop
      with:
        python_version: '3.8.6'
        should_lint: false
        should_test: true
        should_build_docs: true
        should_package: true
        should_run: false
        should_viz: true
        deploy_branch: kedro-action
        verbose: true
```

But despite having should_lint == false, it still seems to execute kedro lint.

![image](https://user-images.githubusercontent.com/39372418/107953296-3da88380-6f9b-11eb-8953-6388ec357ebf.png)

Has anyone had this issue before or knows why lint is being executed?

Thanks
